"""
This type stub file was generated by pyright.
"""

__all__ = ['kmeans_segmentation']
def kmeans_segmentation(image, k, kmask=..., mrf=...): # -> dict[str, Any]:
    """
    K-means image segmentation that is a wrapper around `ants.atropos`

    ANTsR function: `kmeansSegmentation`

    Arguments
    ---------
    image : ANTsImage
        input image

    k : integer
        integer number of classes

    kmask : ANTsImage (optional)
        segment inside this mask

    mrf : scalar
        smoothness, higher is smoother

    Returns
    -------
    ANTsImage

    Example
    -------
    >>> import ants
    >>> fi = ants.image_read(ants.get_ants_data('r16'), 'float')
    >>> fi = ants.n3_bias_field_correction(fi, 2)
    >>> seg = ants.kmeans_segmentation(fi, 3)
    """
    ...

