"""
This type stub file was generated by pyright.
"""

from ..utils import never_fail

"""
Support functionality for using DueCredit
"""
lgr = ...
CITATION_CANDIDATES = ...
@never_fail
def duecredit_dataset(dataset): # -> None:
    """Duecredit cite a dataset if Duecredit is active

    ATM it is an ad-hoc implementation which largely just supports
    extraction of citation information from BIDS extractor
    (datalad-neuroimaging extension) only ATM.
    Generic implementation would require minor harmonization and/or
    support of extraction of relevant information by each extractor.
    """
    ...

