"""
This type stub file was generated by pyright.
"""

from ..utils import auto_repr

"""(comparable) descriptors of the file status

"""
__docformat__ = ...
@auto_repr
class FileStatus:
    """Description of the file status to e.g. check if newer version is available

    """
    def __init__(self, size=..., mtime=..., filename=...) -> None:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __ne__(self, other) -> bool:
        ...
    


