"""
This type stub file was generated by pyright.
"""

import logging
from contextlib import contextmanager

"""Adapters and decorators for vcr
"""
lgr = ...
def use_cassette(path, return_body=..., skip_if_no_vcr=..., **kwargs): # -> CassetteContextDecorator:
    """Adapter so we could create/use custom use_cassette with custom parameters

        Parameters
        ----------
        path : str
          If not absolute path, treated as a name for a cassette under fixtures/vcr_cassettes/
        skip_if_no_vcr : bool
          Rather than running without VCR it would throw unittest.SkipTest
          exception.  Of effect only if vcr import fails (so not in this
          implementation but the one below)
        """
    ...

vcr_lgr = ...
if lgr.getEffectiveLevel() > logging.DEBUG:
    ...
@contextmanager
def externals_use_cassette(name): # -> Generator[None, None, None]:
    """Helper to pass instruction via env variables to use specified cassette

    For instance whenever we are testing custom special remotes invoked by the annex
    but want to minimize their network traffic by using vcr.py
    """
    ...

