"""
This type stub file was generated by pyright.
"""

class LORISTokenGenerator:
    """
    Generate a LORIS API token by making a request to the
    LORIS login API endpoint with the given username
    and password.

    url is the complete URL of the $LORIS/api/$VERSION/login
    endpoint.
    """
    def __init__(self, url=...) -> None:
        ...
    
    def generate_token(self, user=..., password=...): # -> Any:
        ...
    


