"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
__all__ = ["MatReadError", "MatReadWarning", "MatWriteError"]
def __dir__():
    ...

def __getattr__(name):
    ...

