"""
This type stub file was generated by pyright.
"""

from .add_noise_to_image import add_noise_to_image
from .anti_alias import anti_alias
from .bias_correction import abp_n4, n3_bias_field_correction, n3_bias_field_correction2, n4_bias_field_correction
from .crop_image import crop_image, crop_indices, decrop_image
from .denoise_image import denoise_image
from .get_mask import get_mask
from .image_type_cast import image_type_cast
from .hessian_objectness import hessian_objectness
from .histogram_equalize_image import histogram_equalize_image
from .histogram_match_image import histogram_match_image, histogram_match_image2
from .iMath import iMath, iMath_GC, iMath_GD, iMath_GE, iMath_GO, iMath_MC, iMath_MD, iMath_ME, iMath_MO, iMath_canny, iMath_fill_holes, iMath_get_largest_component, iMath_grad, iMath_histogram_equalization, iMath_laplacian, iMath_maurer_distance, iMath_normalize, iMath_pad, iMath_perona_malik, iMath_propagate_labels_through_mask, iMath_sharpen, iMath_truncate_intensity, image_math, multiply_images
from .mask_image import mask_image
from .morphology import morphology
from .pad_image import pad_image
from .reflect_image import reflect_image
from .reorient_image import get_center_of_mass, get_orientation, get_possible_orientations, reorient_image2
from .resample_image import resample_image, resample_image_to_target
from .slice_image import slice_image
from .smooth_image import smooth_image
from .symmetrize_image import symmetrize_image
from .threshold_image import threshold_image
from .weingarten_image_curvature import weingarten_image_curvature

