"""
This type stub file was generated by pyright.
"""

from ants.decorators import image_method

__all__ = ['pad_image']
@image_method
def pad_image(image, shape=..., pad_width=..., value=..., return_padvals=...): # -> tuple[Any, list[int], list[int]]:
    """
    Pad an image to have the given shape or to be isotropic.

    Arguments
    ---------
    image : ANTsImage
        image to pad

    shape : tuple
        - if shape is given, the image will be padded in each dimension
          until it has this shape
        - if shape and pad_width are both None, the image will be padded along
          each dimension to match the largest existing dimension so that it has
          isotropic dimensions.

    pad_width : list of integers or list-of-list of integers
        How much to pad in each direction. If a single list is
        supplied (e.g., [4,4,4]), then the image will be padded by half
        that amount on both sides. If a list-of-list is supplied
        (e.g., [(0,4),(0,4),(0,4)]), then the image will be
        padded unevenly on the different sides

    pad_value : scalar
        value with which image will be padded

    Example
    -------
    >>> import ants
    >>> img = ants.image_read(ants.get_data('r16'))
    >>> img2 = ants.pad_image(img, shape=(300,300))
    >>> mni = ants.image_read(ants.get_data('mni'))
    >>> mni2 = ants.pad_image(mni)
    >>> mni3 = ants.pad_image(mni, pad_width=[(0,4),(0,4),(0,4)])
    >>> mni4 = ants.pad_image(mni, pad_width=(4,4,4))
    """
    ...

