"""
This type stub file was generated by pyright.
"""

class RejectedExecutionError(Exception):
    """Exception raised from MATLAB engine"""
    def __init__(self, message) -> None:
        ...
    
    def __repr__(self): # -> Unknown:
        ...
    


