"""
This type stub file was generated by pyright.
"""

"""
Some utils too deal with peculiar protocols or peculiar ways of handling them

Author: Bertrand Thirion, Ana Luisa Grilo Pinho, 2015
"""
rsvp_language = ...
archi_social = ...
relevant_conditions = ...
def post_process(df, paradigm_id):
    ...

def make_paradigm(onset_file, paradigm_id=...):
    """ Temporary fix """
    ...

