"""
This type stub file was generated by pyright.
"""

import numpy as np

"""
:Module: check_preprocessing
:Synopsis: module for generating post-preproc plots (registration,
segmentation, etc.)
:Author: bertrand thirion, dohmatob elvis dopgima

"""
EPS = np.finfo(float).eps
def plot_spm_motion_parameters(parameter_file, lengths, title=..., output_filename=..., close=..., report_path=...): # -> str | None:
    """ Plot motion parameters obtained with SPM software

    Parameters
    ----------
    parameter_file: string
        path of file containing the motion parameters
    subject_id: string (optional)
        subject id
    titile: string (optional)
        title to attribute to plotted figure
    output_filename: string
        output filename for storing the plotted figure

    """
    ...

def compute_cv(data, mask_array=...):
    ...

def plot_registration(reference_img, coregistered_img, title=..., cut_coords=..., display_mode=..., cmap=..., close=..., output_filename=..., report_path=...): # -> str | None:
    """Plots a coregistered source as bg/contrast for the reference image

    Parameters
    ----------
    reference_img: string
        path to reference (background) image

    coregistered_img: string
        path to other image (to be compared with reference)

    display_mode: string (optional, defaults to 'ortho')
        display_mode param

    cmap: matplotlib colormap object (optional, defaults to spectral)
        colormap to user for plots

    output_filename: string (optional)
        path where plot will be stored

    """
    ...

def plot_segmentation(img, gm_filename, wm_filename=..., csf_filename=..., output_filename=..., cut_coords=..., display_mode=..., cmap=..., title=..., close=..., report_path=...): # -> str | None:
    """
    Plot a contour mapping of the GM, WM, and CSF of a subject's anatomical.

    Parameters
    ----------
    img_filename: string or image object
                  path of file containing image data, or image object simply

    gm_filename: string
                 path of file containing Grey Matter template

    wm_filename: string (optional)
                 path of file containing White Matter template

    csf_filename: string (optional)
                 path of file containing Cerebro-Spinal Fluid template

    """
    ...

