"""
This type stub file was generated by pyright.
"""

from ants.decorators import image_method

__all__ = ['label_geometry_measures']
@image_method
def label_geometry_measures(label_image, intensity_image=...): # -> DataFrame:
    """
    Wrapper for the ANTs funtion labelGeometryMeasures
    
    ANTsR function: `labelGeometryMeasures`

    Arguments
    ---------
    label_image : ANTsImage
        image on which to compute geometry
    intensity_image : ANTsImage (optional)
        image with intensity values

    Returns
    -------
    pandas.DataFrame

    Example
    -------
    >>> import ants
    >>> fi = ants.image_read( ants.get_ants_data('r16') )
    >>> seg = ants.kmeans_segmentation( fi, 3 )['segmentation']
    >>> geom = ants.label_geometry_measures(seg,fi)
    """
    ...

