"""
This type stub file was generated by pyright.
"""

from ants.decorators import image_method

__all__ = ['label_clusters']
@image_method
def label_clusters(image, min_cluster_size=..., min_thresh=..., max_thresh=..., fully_connected=...):
    """
    This will give a unique ID to each connected 
    component 1 through N of size > min_cluster_size

    ANTsR function: `labelClusters`

    Arguments
    ---------
    image : ANTsImage 
        input image e.g. a statistical map
    
    min_cluster_size : integer  
        throw away clusters smaller than this value
    
    min_thresh : scalar
        threshold to a statistical map
    
    max_thresh : scalar
        threshold to a statistical map
    
    fully_connected : boolean
        boolean sets neighborhood connectivity pattern
    
    Returns
    -------
    ANTsImage

    Example
    -------
    >>> import ants
    >>> image = ants.image_read( ants.get_ants_data('r16') )
    >>> timageFully = ants.label_clusters( image, 10, 128, 150, True )
    >>> timageFace = ants.label_clusters( image, 10, 128, 150, False )
    """
    ...

