"""
This type stub file was generated by pyright.
"""

""" Core repository-related functionality

"""
lgr = ...
__all__ = ["repo_from_path"]
def repo_from_path(path): # -> GitRepo | AnnexRepo:
    """Get a Repo instance from a path.

    Parameters
    ----------
    path : path-like
      Root path of the repository.

    Returns
    -------
    Repo
      Repo instance matching the type of the repository at path.

    Raises
    ------
    ValueError
      If no repository could be found at the path, or if its type could not
      be determined.
    """
    ...

