"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Optional

class SaverClass:
    def __init__(self, user: str, host: str, pathToKey: str) -> None:
        ...
    
    def compress(self, filePathsToCompress: list[Path] = ...) -> str:
        ...
    
    def closeSSH(self) -> None:
        ...
    
    def initiateSSHConnection(self, terminateUponConnection: bool = ...) -> Optional[bool]:
        ...
    
    def initiateSCPConnection(self) -> None:
        ...
    
    def saveToServer(self, fileToUploadPath: Path) -> None:
        ...
    


