"""
This type stub file was generated by pyright.
"""

from .matlab import loadmat, savemat, whosmat
from ._netcdf import netcdf_file, netcdf_variable
from ._fortran import FortranEOFError, FortranFile, FortranFormattingError
from ._fast_matrix_market import mminfo, mmread, mmwrite
from ._idl import readsav
from ._harwell_boeing import hb_read, hb_write
from . import arff, harwell_boeing, idl, mmio, netcdf, wavfile
from scipy._lib._testutils import PytestTester

"""
This type stub file was generated by pyright.
"""
__all__ = [s for s in dir() if not s.startswith('_')]
test = ...
