"""
This type stub file was generated by pyright.
"""

import os
from typing import Any, Optional

"""Exception raise on a failed runner command execution
"""
lgr = ...
class CommandError(RuntimeError):
    """Thrown if a command call fails.

    Note: Subclasses should override `to_str` rather than `__str__` because
    `to_str` is called directly in datalad.cli.main.
    """
    def __init__(self, cmd: str | list[str] = ..., msg: str = ..., code: Optional[int] = ..., stdout: str | bytes = ..., stderr: str | bytes = ..., cwd: str | os.PathLike | None = ..., **kwargs: Any) -> None:
        ...
    
    def to_str(self, include_output: bool = ...) -> str:
        ...
    
    def __str__(self) -> str:
        ...
    


