"""
This type stub file was generated by pyright.
"""

from .region_extractor import RegionExtractor, connected_label_regions, connected_regions
from .signal_extraction import img_to_signals_labels, img_to_signals_maps, signals_to_img_labels, signals_to_img_maps
from .parcellations import Parcellations
from .rena_clustering import ReNA, recursive_neighbor_agglomeration
from .hierarchical_kmeans_clustering import HierarchicalKMeans

"""
The :mod:`nilearn.regions` class module includes region extraction
procedure on a 4D statistical/atlas maps and its function.
"""
__all__ = ['connected_regions', 'RegionExtractor', 'connected_label_regions', 'img_to_signals_labels', 'signals_to_img_labels', 'img_to_signals_maps', 'signals_to_img_maps', 'Parcellations', 'ReNA', 'recursive_neighbor_agglomeration', 'HierarchicalKMeans']
