"""
This type stub file was generated by pyright.
"""

__all__ = ["simulate_displacement_field"]
def simulate_displacement_field(domain_image, field_type=..., number_of_random_points=..., sd_noise=..., enforce_stationary_boundary=..., number_of_fitting_levels=..., mesh_size=..., sd_smoothing=...):
    """
    simulate displacement field using either b-spline or exponential transform

    ANTsR function: `simulateDisplacementField`

    Arguments
    ---------
    domain_image : ANTsImage
        Domain image

    field_type : string
        Either "bspline" or "exponential".

    number_of_random_points : integer
        Number of displacement points.

    sd_noise : float
        Standard deviation of the displacement field noise.

    enforce_stationary_boundary : boolean
        Determines fixed boundary conditions.

    number_of_fitting_levels : integer
        Number of fitting levels (b-spline only).

    mesh_size : integer or n-D tuple
        Determines fitting resolution at base level (b-spline only).

    sd_smoothing : float
        Standard deviation of the Gaussian smoothing in mm (exponential only).
        
    Returns
    -------
    ANTs vector image.

    Example
    -------
    >>> import ants
    >>> domain = ants.image_read( ants.get_ants_data('r16'))
    >>> exp_field = ants.simulate_displacement_field(domain, field_type="exponential")
    >>> bsp_field = ants.simulate_displacement_field(domain, field_type="bspline")
    >>> bsp_xfrm = ants.transform_from_displacement_field(bsp_field * 3)
    >>> domain_warped = ants.apply_ants_transform_to_image(bsp_xfrm, domain, domain)
    """
    ...

