"""
This type stub file was generated by pyright.
"""

def preprocess(data, ks, a):
    """
    From data to graph.
    __knn and __w_matrix only use for preprocess
    """
    ...

def Agdl(g, target_cluster_num, kc): # -> list[Any]:
    ...

