"""
This type stub file was generated by pyright.
"""

"""
Name :: UnityId
Shruti Kuber :: skuber
Abhishek Lingwal :: aslingwa
Raunaq Saxena :: rsaxena

Chen, Jie, and Yousef Saad.
"Dense subgraph extraction with application to algorithms detection."
IEEE Transactions on Knowledge and Data Engineering 24.7 (2012): 1216-1230.

Reference internal: https://github.com/imabhishekl/CSC591_Community_Detection
"""
class __Node:
    def __init__(self, name) -> None:
        ...
    


class __Tree:
    def __init__(self) -> None:
        ...
    
    def findLCA_Node(self, src_node, dest_node): # -> None:
        ...
    
    def count_vertices_and_edges(self, edges_list, nodes_list): # -> None:
        ...
    
    def count_vertices_and_edges_wrap(self, root): # -> None:
        ...
    
    def compute_density(self, root): # -> None:
        ...
    
    def extract_sub_graph(self, root, min_density, result): # -> None:
        ...
    


def GDMP2(graph, min_threshold=...): # -> list[Any] | None:
    ...

