"""
This type stub file was generated by pyright.
"""

class Community:
    def __init__(self, G, alpha=...) -> None:
        ...
    
    def add_node(self, node): # -> None:
        ...
    
    def remove_vertex(self, node): # -> None:
        ...
    
    def cal_add_fitness(self, node): # -> Any:
        ...
    
    def cal_remove_fitness(self, node): # -> Any:
        ...
    
    def recalculate(self): # -> None:
        ...
    
    def get_neighbors(self): # -> set[Any]:
        ...
    
    def get_fitness(self): # -> Any:
        ...
    


class LFM_nx:
    def __init__(self, G, alpha) -> None:
        ...
    
    def execute(self): # -> list[Any]:
        ...
    


