"""
This type stub file was generated by pyright.
"""

class MultiCom:
    def __init__(self, g) -> None:
        ...
    
    def execute(self, seed_node, clustering=..., n_steps=..., explored_ratio=...): # -> list[Any]:
        """
        Algorithm for multiple local algorithms detection from a seed node.
        It implements the algorithm presented by Hollocou, Bonald and Lelarge in
        "Multiple Local Community Detection".
        :param g: networkx graph
        :param seed_node: int
            Id of the seed node around which we want to detect communities.
        :param clustering: Scikit-Learn Cluster Estimator
            Algorithm used to cluster nodes in the local embedding space.
            Example: sklearn.cluster.DBSCAN()
        :param n_steps: int, default 5
            Parameter used to control the number of detected communities.
        :param explored_ratio: float, default 0.8
            Parameter used to control the number of new seeds at each step.
        :return:
        seeds: list of int
            Seeds used to detect communities around the initial seed (including this original seed).
        communities: list of set
            Communities detected around the seed node.
        """
        ...
    


