"""
This type stub file was generated by pyright.
"""

def compute_local_pagerank(G, r, p, alpha, epsilon, max_push_count, q): # -> int:
    ...

def cluster_from_sweep(G, p, community): # -> float:
    ...

def pprgrow4(G, seed, alpha, targetvol): # -> tuple[list[Any], float | Any]:
    ...

def pprgrow(args): # -> list[Any]:
    ...

def growclusters(G, seeds, expansion, stopping, nworkers, nruns, alpha, maxexpand, fast): # -> list[Any] | list[list[Any]]:
    ...

def remove_duplicates(G, communities, delta): # -> filter[Any]:
    ...

def neighbor_inflation(G, seeds):
    ...

