"""
This type stub file was generated by pyright.
"""

from logging import getLogger
from .dialog import ConsoleLog, DialogUI, IPythonUI, QuietConsoleLog, SilentConsoleLog, UnderAnnexUI, UnderTestsUI
from ..utils import get_ipython_shell, is_interactive

"""Interactive User Interface (as Dialog/GUI/etc) support

"""
__docformat__ = ...
lgr = ...
KNOWN_BACKENDS = ...
class _UI_Switcher:
    """
    Poor man helper to switch between different backends at run-time.
    """
    def __init__(self, backend=...) -> None:
        ...
    
    def set_backend(self, backend): # -> None:
        ...
    
    @property
    def backend(self): # -> str | None:
        ...
    
    @property
    def ui(self): # -> None:
        ...
    
    def __getattribute__(self, key): # -> Any:
        ...
    
    def __setattr__(self, key, value): # -> None:
        ...
    


ui = ...
