"""
This type stub file was generated by pyright.
"""

"""Various utils oriented to UI"""
def get_terminal_size(): # -> tuple[None, None] | tuple[Any, Any]:
    """Return current terminal size"""
    ...

def get_console_width(default_min=...): # -> Any | Literal[80, 20, 0]:
    """Return console width to use

    In some cases shutil reports it to be 0, so we cannot rely on it
    alone
    """
    ...

