"""
This type stub file was generated by pyright.
"""

def figure_to_svg_bytes(fig): # -> bytes:
    ...

def figure_to_svg_base64(fig): # -> str:
    ...

def figure_to_svg_quoted(fig): # -> str:
    ...

