function [nodeValues] = mapFaceValuesToNodes(faceValues,nodes,faceToNodeMap)

    % This function moves scalar values from FACE CENTROIDS to nodes.
    % It CANNOT assume how a face value got its value (i.e., from two or
    % three nodes of same value). Instead, it requires a matrix to
    % convert. This is generated by loopROIAndAssignLabels function. 
    

    % For each face, return any of the nodeIds (note that it doesn't matter
    % which node is returned, as their values SHOULD be identical).
    allNodeIds = faceToNodeMap(:,2:4);
    
    nodeValues = NaN([length(nodes) 1]);
    for i=1:length(faceToNodeMap)
        faceId=faceToNodeMap(i,1);
        faceNodeIds = faceToNodeMap(i,2:4);
        faceNodeIds(isnan(faceNodeIds)) = [];
        nodeValues(faceNodeIds,1) = faceValues(faceId);
    end

    
    % nodeValues(isnan(nodeValues)) = 0;
end


