"""
This type stub file was generated by pyright.
"""

"""Extended set of commands for working with datasets in a distributed fashion.

**NOTE**

Actually, the above isn't true at the moment. But that is the plan:
<https://github.com/datalad/datalad/issues/3192>
"""
__docformat__ = ...
