"""
This type stub file was generated by pyright.
"""

from ants.decorators import image_method

"""
Functions for plotting ants images
"""
__all__ = ["plot_hist"]
@image_method
def plot_hist(image, threshold=..., fit_line=..., normfreq=..., title=..., grid=..., xlabel=..., ylabel=..., facecolor=..., alpha=...): # -> None:
    """
    Plot a histogram from an ANTsImage

    Arguments
    ---------
    image : ANTsImage
        image from which histogram will be created
    """
    ...

