"""
This type stub file was generated by pyright.
"""

from .ants_image_io import dicom_read, from_numpy, from_numpy_like, image_clone, image_header_info, image_read, image_write, make_image, new_image_like
from .ants_image import ANTsImage, copy_image_info, from_pointer, get_direction, get_origin, get_spacing, is_image, set_direction, set_origin, set_spacing
from .ants_metric_io import create_ants_metric, new_ants_metric, supported_metrics
from .ants_transform_io import create_ants_transform, fsl2antstransform, new_ants_transform, read_transform, transform_from_displacement_field, transform_to_displacement_field, write_transform
from .ants_transform import ANTsTransform, apply_ants_transform, apply_ants_transform_to_image, apply_ants_transform_to_point, apply_ants_transform_to_vector, compose_ants_transforms, get_ants_transform_fixed_parameters, get_ants_transform_parameters, invert_ants_transform, set_ants_transform_fixed_parameters, set_ants_transform_parameters, transform_index_to_physical_point, transform_physical_point_to_index

