"""
This type stub file was generated by pyright.
"""

"""
ANTs ImageToImageMetric class
"""
class ANTsImageToImageMetric:
    """
    ANTsImageToImageMetric class
    """
    def __init__(self, metric) -> None:
        ...
    
    @property
    def precision(self):
        ...
    
    @property
    def dimension(self):
        ...
    
    @property
    def metrictype(self):
        ...
    
    @property
    def is_vector(self):
        ...
    
    @property
    def pointer(self):
        ...
    
    def set_fixed_image(self, image): # -> None:
        """
        Set Fixed ANTsImage for metric
        """
        ...
    
    def set_fixed_mask(self, image): # -> None:
        """
        Set Fixed ANTsImage Mask for metric
        """
        ...
    
    def set_moving_image(self, image): # -> None:
        """
        Set Moving ANTsImage for metric
        """
        ...
    
    def set_moving_mask(self, image): # -> None:
        """
        Set Fixed ANTsImage Mask for metric
        """
        ...
    
    def set_sampling(self, strategy=..., percentage=...): # -> None:
        ...
    
    def initialize(self): # -> None:
        ...
    
    def get_value(self):
        ...
    
    def __call__(self, fixed, moving, fixed_mask=..., moving_mask=..., sampling_strategy=..., sampling_percentage=...):
        ...
    
    def __repr__(self): # -> str:
        ...
    


