"""
This type stub file was generated by pyright.
"""

from cdlib.classes.clustering import Clustering

class EdgeClustering(Clustering):
    """Edge Clustering representation.

    :param communities: list of communities
    :param graph: a networkx/igraph object
    :param method_name: community discovery algorithm name
    :param method_parameters: configuration for the community discovery algorithm used
    :param overlap: boolean, whether the partition is overlapping or not
    """
    def __init__(self, communities: list, graph: object, method_name: str = ..., method_parameters: dict = ..., overlap: bool = ...) -> None:
        ...
    
    def to_edge_community_map(self) -> dict:
        """
        Generate a <edge, list(communities)> representation of the current clustering

        :return: dict of the form <edge, list(communities)>
        """
        ...
    


