"""
This type stub file was generated by pyright.
"""

import h5py

"""Proxy basic file operations (e.g. open) to auto-obtain files upon I/O
"""
_DOT_GIT_DIR = ...
lgr = ...
h5py = ...
class _EarlyExit(Exception):
    """Helper to early escape try/except logic in wrapped open"""
    def __init__(self, msg, *args) -> None:
        ...
    


class AutomagicIO:
    """Class to proxy commonly used API for accessing files so they get automatically fetched

    Currently supports builtin open() and h5py.File when those are read
    """
    def __init__(self, autoget=..., activate=..., check_once=...) -> None:
        """
        
        Parameters
        ----------
        autoget
        activate
        check_once: bool, optional
          To speed things up and avoid unnecessary repeated checks, 
          if True, paths considered for proxying and corresponding repositories
          are remembered, and are not subject to datalad checks on subsequent calls.
          This option is to be used if you do not expect new git repositories to not
          be created and files not to get dropped while operating under 
          AutomagicIO supervision.
        """
        ...
    
    def __enter__(self): # -> Self@AutomagicIO:
        ...
    
    def __exit__(self, exc_type, exc_value, traceback): # -> None:
        ...
    
    @property
    def autoget(self): # -> bool:
        ...
    
    @property
    def active(self): # -> bool:
        ...
    
    def activate(self): # -> None:
        ...
    
    def deactivate(self): # -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    


