"""
This type stub file was generated by pyright.
"""

from .channels import merge_channels, split_channels
from .consistency import allclose, image_physical_space_consistency
from .get_ants_data import get_ants_data, get_data
from .matrix_image import image_list_to_matrix, images_from_matrix, images_to_matrix, matrix_from_images, matrix_to_images, matrix_to_timeseries, timeseries_to_matrix
from .mni2tal import mni2tal
from .ndimage_to_list import list_to_ndimage, ndimage_to_list
from .nifti_to_ants import nifti_to_ants
from .scalar_rgb_vector import rgb_to_vector, scalar_to_rgb, vector_to_rgb

