"""
This type stub file was generated by pyright.
"""

"""
Get local ANTsPy data
"""
__all__ = ['get_ants_data', 'get_data']
def get_data(file_id=..., target_file_name=..., antsx_cache_directory=...): # -> tuple[Literal['r16'], Literal['r27'], Literal['r30'], Literal['r62'], Literal['r64'], Literal['r85'], Literal['ch2'], Literal['mni'], Literal['surf'], Literal['pcasl'], Literal['show']] | str:
    """
    Get ANTsPy test data file

    ANTsR function: `getANTsRData`

    Arguments
    ---------
    name : string
        name of test image tag to retrieve
        Options:
            - 'r16'
            - 'r27'
            - 'r30'
            - 'r62'
            - 'r64'
            - 'r85'
            - 'ch2'
            - 'mni'
            - 'surf'
            - 'pcasl'
    Returns
    -------
    string
        filepath of test image

    Example
    -------
    >>> import ants
    >>> mnipath = ants.get_ants_data('mni')
    """
    ...

get_ants_data = ...
