"""
This type stub file was generated by pyright.
"""

__all__ = ['mni2tal']
def mni2tal(xin): # -> list[Any]:
    """
    mni2tal for converting from ch2/mni space to tal - very approximate.

    This is a standard approach but it's not very accurate.

    ANTsR function: `mni2tal`

    Arguments
    ---------
    xin : tuple
        point in mni152 space.

    Returns
    -------
    tuple

    Example
    -------
    >>> import ants
    >>> ants.mni2tal( (10,12,14) )

    References
    ----------
    http://bioimagesuite.yale.edu/mni2tal/501_95733_More\\%20Accurate\\%20Talairach\\%20Coordinates\\%20SLIDES.pdf
    http://imaging.mrc-cbu.cam.ac.uk/imaging/MniTalairach
    """
    ...

