"""
This type stub file was generated by pyright.
"""

__all__ = ["nifti_to_ants"]
def nifti_to_ants(nib_image): # -> ANTsImage | None:
    """
    Converts a given Nifti image into an ANTsPy image

    Parameters
    ----------
        img: NiftiImage

    Returns
    -------
        ants_image: ANTsImage
    """
    ...

